# Generated by Django 2.2 on 2019-04-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rollnumber', models.CharField(max_length=11)),
                ('branch', models.CharField(max_length=3)),
                ('photo', models.ImageField(upload_to='')),
                ('discription', models.CharField(max_length=6000)),
            ],
        ),
        migrations.CreateModel(
            name='FourthYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rollnumber', models.CharField(max_length=11)),
                ('branch', models.CharField(max_length=3)),
                ('photo', models.ImageField(upload_to='')),
                ('discription', models.CharField(max_length=6000)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('writeup', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NotificationS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('writeup', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NotificationT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('writeup', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NotificationU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('writeup', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SecondYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rollnumber', models.CharField(max_length=11)),
                ('branch', models.CharField(max_length=3)),
                ('photo', models.ImageField(upload_to='')),
                ('discription', models.CharField(max_length=6000)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rollnumber', models.CharField(max_length=11)),
                ('branch', models.CharField(max_length=3)),
                ('photo', models.ImageField(upload_to='')),
                ('discription', models.CharField(max_length=6000)),
            ],
        ),
    ]
