# Generated by Django 2.2 on 2019-04-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='discription',
            field=models.TextField(null=True),
        ),
    ]
