# Generated by Django 2.2 on 2019-04-19 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_events_discription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationf',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='notificationt',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='notificationu',
            name='photo',
        ),
    ]
