# Generated by Django 2.2 on 2019-04-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20190419_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='events',
            name='poster',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
