# Generated by Django 2.2 on 2019-04-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_links_resources'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsWithMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloggername', models.CharField(max_length=20)),
                ('blogsubject', models.CharField(max_length=40)),
                ('blog', models.TextField()),
                ('blogmedia', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='BlogsWithoutMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloggername', models.CharField(max_length=20)),
                ('blogsubject', models.CharField(max_length=40)),
                ('blog', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Links',
        ),
        migrations.DeleteModel(
            name='Resources',
        ),
    ]
